package com.prayercompanion.shared.domain.utils.tracking

enum class TrackedButtons {
    HOME_PRAYED_NOW,
    VIEW_NEXT_DAY_PRAYERS,
    VIEW_PREVIOUS_DAY_PRAYERS,
    STATUS_OVER_VIEW_BAR,
    ISHA_STATUSES_PERIOD_EXPLANATION,

    NEXT_QURAN_READING_SECTION,
    VIEW_FULL_QURAN_READING_SECTION,

    NOTIFICATION_PRAYED_NOW,

    ENABLE_STOP_MEDIA_ON_PRAYER_CALL,
    DISABLE_STOP_MEDIA_ON_PRAYER_CALL,

    NOTIFICATION_PERMISSION_SKIP,
    GOOGLE_SIGN_IN;
}